booklib/Controllers/ModeratorController.cs
using AutoMapper;
using booklib.Entities;
using booklib.Models;
using Microsoft.AspNetCore.Mvc;

namespace booklib.Controllers
{
    public class ModeratorController : Controller
    {
        private readonly DatabaseContext _databaseContext;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;

        public ModeratorController(DatabaseContext databaseContext, IConfiguration configuration, IMapper mapper)
        {
            _databaseContext = databaseContext;
            _configuration = configuration;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BookListPartial()
        {
            List<BookModel> books = 
                _databaseContext.Books.ToList().Select(x=>_mapper.Map<BookModel>(x)).ToList();

            return PartialView("_BookListPartial", books);
        }

        public IActionResult AddNewBookPartial()
        {
            return PartialView("_AddNewBookPartial", new BookModel());
        }

        public IActionResult AddNewBook(BookModel model)
        {
            if (ModelState.IsValid)
            {
                if (_databaseContext.Books.Any(x => x.BookName.ToLower() == model.BookName.ToLower() && x.Author.ToLower() == model.Author.ToLower()))
                {
                    ModelState.AddModelError(nameof(model.BookName), "Bu isimde bir kitap zaten var.");
                    return PartialView("_AddNewBookPartial", model);

                }

                Book book = _mapper.Map<Book>(model);


                _databaseContext.Books.Add(book);
                _databaseContext.SaveChanges();

                return PartialView("_AddNewBookPartial", model);
            }

            return PartialView("_AddNewBookPartial", model);
        }

        public IActionResult DeleteBook(Guid id)
        {
            Book book= _databaseContext.Books.Find(id);

            if (book != null)
            {
                _databaseContext.Books.Remove(book);
                _databaseContext.SaveChanges();
            }

            return BookListPartial();
        }
        //meghabab

        //[HttpPost]
        //public IActionResult Index(BookModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if(_databaseContext.Books.Any(x => x.BookName.ToLower() == model.BookName.ToLower() && x.Author.ToLower() == model.Author.ToLower()))
        //        {
        //            ModelState.AddModelError(nameof(model.BookName), "Kitap mevcut, Stok arttırımı yapabilirsiniz.");
        //            return View(model);
        //        }
        //        //Book book = new Book()
        //        //{
        //        //    BookName = model.BookName,
        //        //    Author = model.Author,
        //        //    BookType = model.BookType,
        //        //    //BookImageFileName = model.BookImageFileName,
        //        //    BookSubject = model.BookSubject,
        //        //    PublishingDate = model.PublishingDate,
        //        //    Stock = model.Stock
        //        //};

        //        Book book = _mapper.Map<Book>(model);

        //        _databaseContext.Books.Add(book);
        //        int affectedRowCount = _databaseContext.SaveChanges();

        //        if (affectedRowCount == 0)
        //        {
        //            ModelState.AddModelError("", "Kitap eklenememiştir.");
        //        }
        //        else
        //        {
        //            return RedirectToAction(nameof(Index));
        //        }
        //    }
        //    return View(model);
        //}
    }
}

booklib/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - booklib</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/booklib.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookLib</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">İletişim</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("moderator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" asp-action="Index" asp-controller="Moderator" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Administrator
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-action="Index" asp-controller="Moderator" class="dropdown-item">Kitap Ekle</a></li>
                                    </ul>
                                </li>
                            }
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ListBook"><i class="fa-solid fa-book me-2"></i>Kitaplarım</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">
                                    <i class="fa-solid fa-user me-2"></i>@User.FindFirst("UserName").Value
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>Giriş Yap</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register"><i class="fa-solid fa-user me-2"></i>Kayıt Ol</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - booklib - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>